### ISSUE TITLE
Run project problem

### ISSUE THREAD

**Issue by fkgl** [sarpreetsingh3131/4dv50e#3]
Hello,

Please I have tried to run this project using both docker and vscode but I face problems.

1. Using docker, when I check localhost it gives me empty response (error), I have tried using wsl and Hyper-V 
2. Using VS Code, it gives me the following error (in Windows 10 pro 64 bit):
Feedback loop started.
1;1638461892882java.io.IOException: Cannot run program "D:\DeltaIoT_simulation_github\4dv50e-master\4dv50e-master\simulation\uppaal-verifyta\verifyta": CreateProcess error=193, %1 n?est pas une application Win32 valide
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at java.base/java.lang.Runtime.exec(Runtime.java:589)
        at java.base/java.lang.Runtime.exec(Runtime.java:413)
        at java.base/java.lang.Runtime.exec(Runtime.java:310)
        at smc.ExecuteCommand.call(ExecuteCommand.java:30)
        at smc.ExecuteCommand.call(ExecuteCommand.java:1)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: CreateProcess error=193, %1 n?est pas une application Win32 valide
        at java.base/java.lang.ProcessImpl.create(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:478)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
        ... 10 more

I will be grateful if you can help me.
Thanks

**Comment by sarpreetsingh3131** [comment]
Hey, I will investigate and come back to you.

**Comment by sarpreetsingh3131** [comment]
Hi, if you ran the bigger motes setup than you need to increase your runtime memory.

**Comment by fkgl** [comment]
Hi, thank you, I'll try that.
